httpd:
  build: .
  links:
    - maria_db:db
  ports:
    - 8180:80
  volumes:
    - ./:/var/www/html
maria_db:
  container_name: mariadb
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: docker
  ports:
    - 3305:3306
  expose:
    - "3305"
  volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - maria_db:db
  ports:
    - 8181:80
  environment:
    PMA_USER: root
    PMA_PASSWORD: docker